#!/usr/bin/env python3
"""Generate page_name -> slug mapping for the redirect site."""

import csv
import json
from pathlib import Path
from typing import Dict


ROOT = Path(__file__).resolve().parents[1]
INVENTORY_CSV = ROOT / "pukiwiki_page_inventory.csv"
OUT_JS = ROOT / "www.redirect" / "html" / "page-map.js"


def slug_from_converted_filename(converted_filename: str) -> str:
    # _posts/YYYY-MM-DD-ULID.md -> ULID
    stem = Path(converted_filename).stem
    parts = stem.split("-")
    if len(parts) >= 4:
        return parts[-1]
    return stem


def main() -> None:
    redirect_map = {}  # type: Dict[str, str]
    with INVENTORY_CSV.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row.get("convert_target") != "true":
                continue
            page_name = row["page_name"]
            converted_filename = row["converted_filename"]
            redirect_map[page_name] = slug_from_converted_filename(converted_filename)

    OUT_JS.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(redirect_map, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    content = (
        "// Generated by scripts/build_redirect_map.py. DO NOT EDIT MANUALLY.\n"
        "window.PAGE_REDIRECT_MAP = "
        + payload
        + ";\n"
    )
    OUT_JS.write_text(content, encoding="utf-8")
    print(f"wrote {OUT_JS} ({len(redirect_map)} entries)")


if __name__ == "__main__":
    main()
